apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: meta-fetcher-api
  name: meta-fetcher-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: meta-fetcher-api
  template:
    metadata:
      labels:
        service: meta-fetcher-api
    spec:
      containers:
        - image: maksim1111/meta-fetcher-api:latest
          name: meta-fetcher-api
          imagePullPolicy: IfNotPresent
          command: [ "/app/main" ]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: meta-fetcher-api
  name: meta-fetcher-api
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    service: meta-fetcher-api
